pipelines:
  default:
    - step:
        name: Build Docker Image
        services:
          - docker
        image: google/cloud-sdk:latest
        script:
          - echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/gcloud-api.json
          - gcloud auth activate-service-account --key-file=/tmp/gcloud-api.json --project=$CI_GCP_STAGING_PROJECT_ID
          - gcloud auth configure-docker asia.gcr.io
          - export DOCKER_BUILDKIT=0
          - docker build --platform amd64 --tag analytics-frontend:$BITBUCKET_COMMIT -f ./Dockerfile .
          - docker tag docker.io/library/analytics-frontend:$BITBUCKET_COMMIT asia.gcr.io/backend-staging-370410/analytics-frontend:$BITBUCKET_COMMIT
          - docker push asia.gcr.io/backend-staging-370410/analytics-frontend:$BITBUCKET_COMMIT
    - step:
        name: Deploy Staging GCP
        trigger: "manual"
        services:
          - docker
        image: google/cloud-sdk:latest
        script:
          - echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/gcloud-api.json
          - gcloud auth activate-service-account --key-file=/tmp/gcloud-api.json --project=$CI_GCP_STAGING_PROJECT_ID
          - gcloud auth configure-docker asia.gcr.io
          - export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          - gcloud container clusters get-credentials staging-cluster-01 --region asia-south2 --project backend-staging-370410
          - sed -i "s|{{image}}|asia.gcr.io/backend-staging-370410/analytics-frontend:$BITBUCKET_COMMIT|g" ./k8s/deployment.yml
          - KUBECONFIG=~/.kube/config kubectl apply -f ./k8s/deployment.yml
