apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: analytics-frontend
    app.kubernetes.io/name: analytics-frontend
    process: web
  name: analytics-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: analytics-frontend
      process: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: analytics-frontend
        process: web
    spec:
      containers:
        - env:
            - name: DB
              value: ""
          image: {{image}}
          command: ["npm", "run", "start"]
          imagePullPolicy: Always
          name: analytics-frontend
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1000m"
              memory: "4Gi"
            requests:
              cpu: "1000m"
              memory: "4Gi"
