version: "3"
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  postgres:
    build:
      context: ./storage
    ports:
      - 5432:5432
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "mql"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
        postgres:
          condition: service_healthy

networks:
  mynetwork:
    name: my-shared-db-network

volumes:
  postgres-data:
