apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-backend-configmap
data:
  DATABASE_URL: "postgresql://shuru:password@10.190.0.6:5432/analytics"
  SECRET_KEY: "this-is-shuru-internal-project"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  OPENAI_API_KEY: "sk-random-key"
